---
# Default values for notebooks-accounting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

debug: false

# Accounting parameters
accounting:
  # (empty value to disable accounting)
  schedule: "23 */6 * * *"
  sitename: EGI-NOTEBOOKS
  cloudType: EGI Notebooks
  service:

