---
# Default values for notebooks-accounting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

debug: false

# Accounting parameters
accounting:
  # (empty value to disable accounting)
  schedule: 23 */6 * * *
  sitename: EGI-NOTEBOOKS
  cloudType: EGI Notebooks
  service:

  # catchall FQAN for values not specified in the fqan mapping
  default_fqan: vo.notebooks.egi.eu

  # Pod dictionary key used for fqan mapping
  # (primary_group, namespace, image_id, ...)
  fqan_key: primary_group

  #
  # Mapping to get the result FQAN
  #
  # VO1: value1,value2,...
  # VO2: value3,value4,...
  # ...
  #
  # Values are taken from the pod according to the selected fqan_key.
  #
  fqan: {}

# Prometheus endpoint
prometheus:
  url: "http://prometheus-server.prometheus.svc.cluster.local"

# Permanent storage, mounted at '/accounting'
storage:
  pvcName: shared-accounting-pvc
  size: 2Gi
  # directory pool for APEL dumps (empty value to disable)
  apelSpool:
  # storage to local sqlite database (empty value to disable)
  notebooksDb: /accounting/notebooks.db

image:
  repository: eginotebooks/svc-accounting
  # pullPolicy:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# EOSC accounting paramters
eosc:
  # (empty value to disable)
  schedule: 42 3 * * *
  # configuration for the EOSC accounting
  tokenUrl:
  clientId:
  clientSecret:
  accountingUrl:
  installationId:
  flavorMetrics: {}

# APEL sender parameters
ssm:
  # (empty value to disable)
  schedule:
  image:
    repository: stfc/ssm
    tag: release-3.2.1
    pullPolicy: IfNotPresent
  hostcert:
  hostkey:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

nodeSelector: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
