# Default values for notebook-accounting.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  enabled: true

prometheus:
  url: http://prom-prometheus-server.default.svc.cluster.local

storage:
  pvcName: shared-accounting-pvc
  size: 1Gi

watcher:
  replicaCount: 1
  image:
    repository: enolfc/accounting 
    tag: v0.0
    pullPolicy: IfNotPresent

dumper:
  schedule: "23 */6 * * *"
  image:
    repository: enolfc/accounting 
    tag: v0.0
    pullPolicy: IfNotPresent
  sitename: "EGI-NOTEBOOKS"
  vo: "vo.access.egi.eu"
  cloudType: "EGI Notebooks"
  service:

ssm:
  schedule: "38 */8 * * *"
  image:
    repository: stfc/ssm
    tag: release-2.4.0
    pullPolicy: IfNotPresent
  hostcert:
  hostkey:



resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
