sudo: required
services:
- docker
jobs:
  include:
  - stage: build docker images
    script:
    - export TAG=$(if [ "x$TRAVIS_TAG" != "x" ]; then echo "$TRAVIS_TAG"; else git
      rev-parse --short HEAD; fi)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_REPO/accounting .
    - docker tag $DOCKER_REPO/accounting $DOCKER_REPO/accounting:$TAG
    after_success:
    - docker push $DOCKER_REPO/accounting
    - docker push $DOCKER_REPO/accounting:$TAG
env:
  global:
  - DOCKER_REPO=eginotebooks
  - secure: pJ4UyyLMiVu/+F2SCJ9icscfDXxrFpJDTr1FeqoMs66BR8vEGUpKBhG8DC2uoGtzGwqrfTpZftYR9qSLkz1OOUvyRmOs4eCB87wMD8HydAOb4mT7ymLiRXT/bpeSjiDeTZZ7KGNHZcTWrpDzlvGqwhA7NwKl8Q9wPbm/NvCr5V7FVPipfIGK90x9nZqyMkZGCQ7vUcuF9rM3DDGrJdl+8YghT35HSRmnNJmbLcq5kdb9KzgesEpnvGdfLKKwprYtR8N6Y7LXcmco8Ydu0UpxSrphKaTlKdl9924FCA+asHEXMC2JLqBpCTLf5v/Q8NVbn8R3XrA5xziRqss6Hgq/yvvkvncCTN6iXjV9kEY7TeLkEnKB160yiRF6KN1tXyynXXFC2N6iOr5ju8QvYlADRCoDaSfpSUwDGUgkv8MSLfP+pztJRzPfF4NzR2G/l+3Ll/ePS2TGpMmP1w/LhD07i+OzhGb/VFtOGjbONAsbSJXMSN/mNY5673U8WArHkWNvPZwVBthcI/LRPIE35KpUobuinRe7nJbUkN0e8P9XfOfinqtFREQclsGR04vt9Vl0zn/Hvj6zbwjodRAO7rSQShwbBVldPXLmI1p4Mtq4H8WDYiI/DaGG8WFKVHdOJw9paODfiezZSlVMKLz5yX87DyEZ1dFZbROns7lnxFOSIYY=
  - secure: mFLxc5eEBcxToRqZkNs6z0cD0yCNusg3r7Qti2rjo4X3/+GAlTwUHBYi4xEuSyv20snyoDbP0bM2b1pl82IIwj8yh5e0GtJNaepoiEBDijHe9+YcTZNn6BLzTKbLkcQ/+GA0bCobwN1icyzcYFsQ1pp1/kVKLHKyghTNqhPEYwe6Q+dVAUmklMthba3tLAPwAaO2jDSXsOdnT2GPEQTJa5UjDApuOJ7Q6CANft8B8Fl2UAzhF5hVrIC9YDCzijkU5pJNtHcSLVYZhJv/+1/LGh354byL6txIjCFzcZV7Eo8a7bVA8JerHRikdTArj9lvXyhZRi+e6m4CIWDkPCzGU3HOVLY8mv4DIJZHmHmf2tKLPIk18CJWzgfv48rCw/zl9yj2yky1vQHwSnKvHldcSoIfAItvPSsibdjedj2w5qmgXKkH7R477r29OtCjOg0Z4rpfuy1RJ5A18cGGhernjBdCk0V5uFkPdwKhyIJYu+FMJcox2l5wbzrWWd0ooVLc441aT5LX0Ll+6x+glP3FODgw7kV/cS7es3HF3QhxAEuHVPOg35w0mykzyuWfeH4sDjDo/A7u/2lYoWiuFj3dKJ4J6kjL1kB6bWFZs/rVsfIr7WnvbUbb8YQuZ+Ye18NuquCjSD/wAfVPHVbufEHCD50neV0VlURYZprwl+auX1E=
