language: python
python:
  - 3.6
git:
  depth: false
services:
  - docker
jobs:
  include:
  - stage: build chart and publish
    install:
    - pip3 install -r dev-requirements.txt
    - mkdir -p bin
    - curl -ssL https://storage.googleapis.com/kubernetes-helm/helm-v2.3.0-linux-amd64.tar.gz | tar -xz -C . --strip-components 1 linux-amd64/helm
    - chmod +x helm
    - sudo mv helm /usr/local/bin
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - chartpress --push --publish-chart
env:
  global:
  - secure: pJ4UyyLMiVu/+F2SCJ9icscfDXxrFpJDTr1FeqoMs66BR8vEGUpKBhG8DC2uoGtzGwqrfTpZftYR9qSLkz1OOUvyRmOs4eCB87wMD8HydAOb4mT7ymLiRXT/bpeSjiDeTZZ7KGNHZcTWrpDzlvGqwhA7NwKl8Q9wPbm/NvCr5V7FVPipfIGK90x9nZqyMkZGCQ7vUcuF9rM3DDGrJdl+8YghT35HSRmnNJmbLcq5kdb9KzgesEpnvGdfLKKwprYtR8N6Y7LXcmco8Ydu0UpxSrphKaTlKdl9924FCA+asHEXMC2JLqBpCTLf5v/Q8NVbn8R3XrA5xziRqss6Hgq/yvvkvncCTN6iXjV9kEY7TeLkEnKB160yiRF6KN1tXyynXXFC2N6iOr5ju8QvYlADRCoDaSfpSUwDGUgkv8MSLfP+pztJRzPfF4NzR2G/l+3Ll/ePS2TGpMmP1w/LhD07i+OzhGb/VFtOGjbONAsbSJXMSN/mNY5673U8WArHkWNvPZwVBthcI/LRPIE35KpUobuinRe7nJbUkN0e8P9XfOfinqtFREQclsGR04vt9Vl0zn/Hvj6zbwjodRAO7rSQShwbBVldPXLmI1p4Mtq4H8WDYiI/DaGG8WFKVHdOJw9paODfiezZSlVMKLz5yX87DyEZ1dFZbROns7lnxFOSIYY=
  - secure: mFLxc5eEBcxToRqZkNs6z0cD0yCNusg3r7Qti2rjo4X3/+GAlTwUHBYi4xEuSyv20snyoDbP0bM2b1pl82IIwj8yh5e0GtJNaepoiEBDijHe9+YcTZNn6BLzTKbLkcQ/+GA0bCobwN1icyzcYFsQ1pp1/kVKLHKyghTNqhPEYwe6Q+dVAUmklMthba3tLAPwAaO2jDSXsOdnT2GPEQTJa5UjDApuOJ7Q6CANft8B8Fl2UAzhF5hVrIC9YDCzijkU5pJNtHcSLVYZhJv/+1/LGh354byL6txIjCFzcZV7Eo8a7bVA8JerHRikdTArj9lvXyhZRi+e6m4CIWDkPCzGU3HOVLY8mv4DIJZHmHmf2tKLPIk18CJWzgfv48rCw/zl9yj2yky1vQHwSnKvHldcSoIfAItvPSsibdjedj2w5qmgXKkH7R477r29OtCjOg0Z4rpfuy1RJ5A18cGGhernjBdCk0V5uFkPdwKhyIJYu+FMJcox2l5wbzrWWd0ooVLc441aT5LX0Ll+6x+glP3FODgw7kV/cS7es3HF3QhxAEuHVPOg35w0mykzyuWfeH4sDjDo/A7u/2lYoWiuFj3dKJ4J6kjL1kB6bWFZs/rVsfIr7WnvbUbb8YQuZ+Ye18NuquCjSD/wAfVPHVbufEHCD50neV0VlURYZprwl+auX1E=
  - secure: x7tQHxHgFEK0hUcHrs/7FWhBV/vBcQSdZFDcaDRkyQuDLJSg62OVbibaQE+NpnNqEClfK3kxUuIN3s8RXqOECZ9lmDYePDgJeRPGpVB+1+FOnFNLwYlGTGFik1YlJRARyPakk8VskASU+IHda7lPKYJfSL1kb/PFWI+z8iuaEKIElT/4pFQOuOtgjTV3rWZocMMm2HhWHIlahpdcQl1D1qBoa11ue5+USpBiK9++yewBOWA//jSBhgFoFNPdvBc3vPhtIhU/aRIFwDe8mmEguvrnVaK7nrhuNHVw1dUQh5NTJxBF2UBiFGWAN7CPDrTpURVq8j3muHXH3OqDfQomCoExcmY6IJHwLNi/2qV41AS/fRbaDYkHikGx/SlXU9Mb+jSfKFoeoOret9PJn7T9reBgvTkgCRTj+QSUBDs3XWggNP864dZk7oOtw/lAJo3+ABd3MTmH4GIVuwjRj7Loqo5s0Vh5YriD3wkHb6vePDhOuOuZ/CgApL0RGSdpsqltFmrTnYk2iaaYvwGsZdY/TEAoz6Tq2K3p426DibtJRwGSWkYiRYDfcroF0zIcyNhOos0ze6t8w1YD0T/HyDE39ta6QBr3bJfo9oYWwroUdZGJiE/LhHwlq8ozz5YgbrNICvFOcdSp9ia94QUHDQJceUyDyA3xa91BWK6EFfHLcLo=
