kind: ConfigMap
apiVersion: v1
metadata:
  name: notebooks-accounting-service-config
  labels:
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  PROMETHEUS_URL: {{ .Values.prometheus.url }}
  APEL_SPOOL: /accounting/ssm
  NOTEBOOK_DB: /accounting/notebooks.sqlite
  SITENAME: {{ .Values.dumper.sitename }}
  VO: {{ .Values.dumper.vo }}
  CLOUD_TYPE: {{ .Values.dumper.cloudType }}
  SERVICE: {{ .Values.dumper.service }}
