apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: notebooks-accounting-dump
  labels:
    app: {{ template "notebook-accounting.name" . }}
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  schedule: {{ .Values.dumper.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: dumper 
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/usr/local/bin/egi-notebooks-dumper"]
            envFrom:
            - configMapRef:
                name: notebooks-accounting-service-config 
            volumeMounts:
            - mountPath: /accounting
              name: shared-accounting-vol
            resources:
{{ toYaml .Values.resources | indent 14 }}
          volumes:
          - name: shared-accounting-vol
            persistentVolumeClaim:
              claimName: {{ .Values.storage.pvcName }} 
        {{- with .Values.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
        {{- end }}
