---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  labels:
    {{- include "notebooks-accounting.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if hasKey .Values.storage "className" }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
