{{- if .Values.rbac.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebooks-accounting
  labels:
    app: {{ template "notebook-accounting.name" . }}
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: notebooks-accounting
  labels:
    app: {{ template "notebook-accounting.name" . }}
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"] 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: notebooks-accounting
  labels:
    app: {{ template "notebook-accounting.name" . }}
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: notebooks-accounting
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: notebooks-accounting 
  apiGroup: rbac.authorization.k8s.io
{{- end }}
