kind: Secret
apiVersion: v1
metadata:
  name: notebooks-accounting-ssm-hostcerts 
  labels:
    app: {{ template "notebook-accounting.name" . }}
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  hostcert.pem: {{ (required "Host cert must be a valid pem certificate!" .Values.ssm.hostcert) | b64enc | quote }}
  hostkey.pem: {{ (required "Host key must be a valid key!" .Values.ssm.hostkey) | b64enc | quote }}
