{{- if .Values.ssm.schedule }}
kind: Secret
apiVersion: v1
metadata:
  name: notebooks-accounting-ssm-hostcerts
  labels:
    {{- include "notebooks-accounting.labels" . | nindent 4 }}
type: Opaque
data:
  hostcert.pem: {{ (required "Host cert must be a valid pem certificate!" .Values.ssm.hostcert) | b64enc | quote }}
  hostkey.pem: {{ (required "Host key must be a valid key!" .Values.ssm.hostkey) | b64enc | quote }}
{{- end }}
