apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebooks-accounting-watcher
  labels:
    app: {{ template "notebook-accounting.name" . }}
    chart: {{ template "notebook-accounting.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.watcher.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "notebook-accounting.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "notebook-accounting.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: notebooks-accounting 
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-watcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/egi-notebooks-watcher"]
          envFrom:
          - configMapRef:
              name: notebooks-accounting-service-config 
          volumeMounts:
          - mountPath: /accounting
            name: shared-accounting-vol
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: shared-accounting-vol
        persistentVolumeClaim:
          claimName: {{ .Values.storage.pvcName }} 
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
