---
name: Lint

on: [pull_request, push]

permissions: read-all

jobs:
  super-lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_EXCLUDE: notebooks-accounting/templates/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Fail on errors
          DISABLE_ERRORS: false
          # this is a bit too much for this repo
          VALIDATE_CHECKOV: false
          # not needed for this repo
          VALIDATE_JSCPD: false
          # problem with dependencies
          VALIDATE_PYTHON_MYPY: false
          # this is a bit too much for this repo
          VALIDATE_PYTHON_PYLINT: false
